---
title: "Gompit Regresson Simulation Study"
author: "Laurens Bogaardt"
date: "2023-06-08"
output:
  html_document:
    df_print: paged
    fig_width: 10
    fig.align: center
    toc: true
    toc_depth: 4
    toc_float: true
    theme: united
    code_folding: show
---

# Introduction

This document describes ...

The document uses the package _tidyverse_.

```{r results = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(evd)
```

```{r}
ggplot() +
  geom_function(
    fun = dlogis,
    colour = "red"
  ) +
  geom_function(
    fun = dgumbel,
    args = list(scale = dgumbel(0) / dlogis(0)),
    colour = "green"
  ) +
  geom_function(
    fun = plogis,
    colour = "red",
    linetype = "dashed"
  ) +
  geom_function(
    fun = pgumbel,
    args = list(scale = dgumbel(0) / dlogis(0)),
    colour = "green",
    linetype = "dashed"
  ) +
  xlim(-5, 5)
```

```{r}
ggplot() +
  geom_function(
    fun = function(x){pgumbel(-log(x))},
    colour = "green"
  ) +
  geom_function(
    fun = function(x){exp(-x)},
    colour = "red",
    linetype = "dashed"
  ) +
  xlim(0, 5)
```

# Functions

```{r}
generate.and.estimate.gompit.regression <- function(n, intercept, slope) {
  x <- rnorm(n)
  y <- intercept + slope * x + rgumbel(n)
  c <- y > 0
  model <- glm(
    formula = c ~ 1 + x,
    family = binomial(link = "cloglog")
  )
  result <- data.frame(
    intercept = coef(model)[[1]],
    slope = coef(model)[[2]]
  )
  return(result)
}
```

# Parameters

```{r}
parameters <- tibble(
  parameter.set = seq(4),
  n.data = c(200, 800, 200, 200),
  intercept = c(1, 1, -0.5, 1),
  slope = c(0.5, 0.5, 0.5, -0.25)
)
parameters
```

# Estimation

```{r}
estimated.parameters <- parameters %>%
  expand_grid(
    run = seq(200)
  ) %>%
  rowwise() %>%
  mutate(
    generate.and.estimate.gompit.regression(
      n = n.data,
      intercept = intercept,
      slope = slope
    )
  ) %>%
  ungroup()
estimated.parameters
```

# Visualise Estimated Paramaters

```{r}
ggplot() +
  geom_density(
    mapping = aes(
      x = value,
      y = after_stat(scaled),
      fill = name
    ),
    data = estimated.parameters %>%
      pivot_longer(
        cols = c("intercept", "slope")
      ),
    alpha = 0.3
  ) +
  geom_vline(
    mapping = aes(
      xintercept = value,
      col = name
    ),
    data = parameters %>%
      pivot_longer(
        cols = c("intercept", "slope")
      )
  ) +
  facet_grid(
    cols = vars(name),
    rows = vars(parameter.set),
    scales = "free"
  )
```

# Visualise Parameter Correlations

```{r}
ggplot(
  mapping = aes(
    x = parameter.1,
    y = parameter.2,
    fill = correlation,
    label = sprintf("%.2f", correlation)
  ),
  data = estimated.parameters %>%
    group_by(parameter.set) %>%
    reframe(
      expand_grid(
        parameter.1 = c("intercept", "slope"),
        parameter.2 = c("intercept", "slope")
      ),
      correlation = c(cor(data.frame(intercept, slope)))
    )
) +
  geom_tile(alpha = 0.5) +
  geom_text() +
  scale_fill_viridis_c() +
  guides(fill = "none") +
  labs(
    x = NULL,
    y = NULL
  ) +
  facet_wrap(
    facets = vars(parameter.set)
  )
```

```{r}
ggplot(
  mapping = aes(
    x = intercept,
    y = slope
  ),
  data = estimated.parameters,
    alpha = 0.1
) +
  geom_point() +
  geom_smooth(
    formula = y ~ x,
    method = "lm"
  ) +
  geom_vline(
    mapping = aes(
      xintercept = intercept
    ),
    data = parameters
  ) +
  geom_hline(
    mapping = aes(
      yintercept = slope
    ),
    data = parameters
  ) +
  facet_wrap(
    facets = vars(parameter.set),
    scales = "free"
  )
```
