---
title: "B-Splines"
author: "Laurens Bogaardt"
date: "2024-04-01"
output:
  html_document:
    df_print: paged
    fig_width: 10
    fig.align: center
    toc: true
    toc_depth: 4
    toc_float: true
    theme: united
    code_folding: show
---

<style>
body{text-align: justify}
</style>

# Introduction

```{r results = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(splines)
set.seed(123)
```

# Functions

```{r}
evenly.spread.internal.knots <- function(df, degree) {
  step <- 1 / (df - degree)
  if (step == 1) {
    result <- NULL
  } else {
    result <- seq(step, 1 - step, step)
  }
  return(result)
}
```

```{r}
evenly.spread.knots <- function(df, degree) {
  step <- 1 / (df - degree)
  if (step == 1) {
    result <- c(rep(0, degree + 1), rep(1, degree + 1))
  } else {
    result <- c(rep(0, degree), seq(0, 1, 1 / (df - degree)), rep(1, degree))
  }
  return(result)
}
```

```{r}
basisSpline <- function(x, i, knots, degree) {
  if (x < knots[i]) {
    result <- 0
  } else if (x >= knots[i + degree + 1]) {
    result <- 0
  } else if (degree == 0) {
    result <- 1
  } else {
    d1 <- knots[i + degree] - knots[i]
    w1 <- ifelse(d1 == 0, 0, (x - knots[i]) / d1)
    d2 <- knots[i + degree + 1] - knots[i + 1]
    w2 <- ifelse(d2 == 0, 0, (x - knots[i + degree + 1]) / d2)
    result <- w1 * basisSpline(x, i, knots, degree - 1) - w2 * basisSpline(x, i + 1, knots, degree - 1)
  }
  return(result)
}
```

```{r}
bSpline <- function(x, x.start, x.end, weights, degree) {
  x <- (x - x.start) / (x.end - x.start)
  x <- min(1 - 10 ^ - 9, max(0, x))
  df <- length(weights)
  knots <- evenly.spread.knots(df, degree)
  result <- 0
  for (i in seq(df)) {
    result <- result + weights[i] * basisSpline(x, i, knots, degree)
  }
  return(result)
}
```

```{r}
bSpline2D <- function(x1, x1.start, x1.end, x2, x2.start, x2.end, weights, degree1, degree2) {
  x1 <- (x1 - x1.start) / (x1.end - x1.start)
  x2 <- (x2 - x2.start) / (x2.end - x2.start)
  x1 <- min(1 - 10 ^ - 9, max(0, x1))
  x2 <- min(1 - 10 ^ - 9, max(0, x2))
  df1 <- nrow(weights)
  df2 <- ncol(weights)
  knots1 <- evenly.spread.knots(df1, degree1)
  knots2 <- evenly.spread.knots(df2, degree2)
  result <- 0
  for (i1 in seq(df1)) {
    for (i2 in seq(df2)) {
      result <- result + weights[i1, i2] * basisSpline(x1, i1, knots1, degree1) * basisSpline(x2, i2, knots2, degree2)
    }
  }
  return(result)
}
```

# Bases Data

```{r}
data <- tibble(
  df = seq(2, 6)
) %>%
  group_by(df) %>%
  summarise(
    degree = seq(df - 1),
    .groups = "drop"
  ) %>%
  group_by(df, degree) %>%
  summarise(
    i = seq(df),
    .groups = "drop"
  ) %>%
  group_by(df, degree, i) %>%
  expand_grid(
    x = seq(0, 1 - 10 ^ - 9, length.out = 50)
  ) %>%
  group_by(df, degree, i, x) %>%
  mutate(
    y1 = basisSpline(x, i, evenly.spread.knots(df, degree), degree),
    y2 = c(bs(x = x, knots = evenly.spread.internal.knots(df, degree), df = df, degree = degree, intercept = TRUE, Boundary.knots = c(0, 1))[,i])
  ) %>%
  ungroup()
data
```

# Visualise Bases

```{r}
ggplot() +
  geom_line(
    mapping = aes(
      x = x,
      y = y1,
      col = as.factor(i)
    ),
    data = data
  ) +
  geom_point(
    mapping = aes(
      x = x,
      y = y2,
      col = as.factor(i)
    ),
    data = data
  ) +
  facet_grid(
    rows = vars(paste0("df: ", df)),
    cols = vars(paste0("degree: ", degree))
  ) +
  labs(
    x = "x",
    y = "y",
    col = "basis"
  )
```

# Compare Bases

```{r}
x <- runif(1, 0, 1)
df <- sample(seq(4, 8), 1)
degree <- sample(seq(2, df - 1), 1)
knots <- evenly.spread.knots(df, degree)
i <- sample(seq(df), 1)
y1 <- basisSpline(x, i, knots, degree)
y2 <- c(bs(x = x, knots = evenly.spread.internal.knots(df, degree), df = df, degree = degree, intercept = TRUE, Boundary.knots = c(0, 1))[,i])
diff <- abs(y1 - y2) < 0.0001
data.frame(
  x = x,
  df = df,
  degree = degree,
  i = i,
  y1 = y1,
  y2 = y2,
  diff = diff
)
```

# Smooth Function Data

```{r}
weights <- runif(9)
data2 <- data %>%
  group_by(df, degree, x) %>%
  reframe(
    y1 = bSpline(x, 0, 1, weights[i], unique(degree)),
    y2 = c(bs(x = x, knots = evenly.spread.internal.knots(unique(df), unique(degree)), df = unique(df), degree = unique(degree), intercept = TRUE, Boundary.knots = c(0, 1)) %*% weights[i])
  )
data2
```

# Visualise Smooth Function

```{r}
ggplot() +
  geom_line(
    mapping = aes(
      x = x,
      y = y1
    ),
    data = data2
  ) +
  geom_point(
    mapping = aes(
      x = x,
      y = y2
    ),
    data = data2
  ) +
  facet_grid(
    rows = vars(df),
    cols = vars(degree)
  )
```

# Compare Smooth Function

```{r}
x.start <- runif(1, -2, 3)
x.end <- x.start + runif(1, 0.1, 3)
x <- runif(1, x.start, x.end)
df <- sample(seq(4, 8), 1)
degree <- sample(seq(2, df - 1), 1)
weights <- runif(df)
y1 <- bSpline(x, x.start, x.end, weights, degree)
y2 <- c(bs(x = x, knots = x.start + (x.end - x.start) * evenly.spread.internal.knots(df, degree), df = df, degree = degree, intercept = TRUE, Boundary.knots = c(x.start, x.end)) %*% weights)
diff <- abs(y1 - y2) < 0.0001
data.frame(
  x.start = x.start,
  x.end = x.end,
  x = x,
  df = df,
  degree = degree,
  y1 = y1,
  y2 = y2,
  diff = diff
)
```

# Compare Two-Dimensional Function

```{r}
x1.start <- runif(1, -2, 3)
x2.start <- runif(1, -2, 3)
x1.end <- x1.start + runif(1, 0.1, 3)
x2.end <- x2.start + runif(1, 0.1, 3)
x1 <- runif(1, x1.start, x1.end)
x2 <- runif(1, x2.start, x2.end)
df1 <- sample(seq(4, 8), 1)
df2 <- sample(seq(4, 8), 1)
degree1 <- sample(seq(2, df1 - 1), 1)
degree2 <- sample(seq(2, df2 - 1), 1)
weights.matrix <- matrix(runif(df1 * df2), df1, df2)
y1 <- bSpline2D(x1, x1.start, x1.end, x2, x2.start, x2.end, weights.matrix, degree1, degree2)
y2 <- c(bs(x = x1, knots = x1.start + (x1.end - x1.start) * evenly.spread.internal.knots(df1, degree1), df = df1, degree = degree1, intercept = TRUE, Boundary.knots = c(x1.start, x1.end)) %*% weights.matrix %*% c(bs(x = x2, knots = x2.start + (x2.end - x2.start) * evenly.spread.internal.knots(df2, degree2), df = df2, degree = degree2, intercept = TRUE, Boundary.knots = c(x2.start, x2.end))))
diff <- abs(y1 - y2) < 0.0001
data.frame(
  x1.start = x1.start,
  x2.start = x2.start,
  x1.end = x1.end,
  x2.end = x2.end,
  x1 = x1,
  x2 = x2,
  df1 = df1,
  df2 = df2,
  degree1 = degree1,
  degree2 = degree2,
  y1 = y1,
  y2 = y2,
  diff = diff
)
```
