---
title: "Local Sensitivity Analysis And First-Order Uncertainty Quantification"
author: "Laurens Bogaardt"
date: "2024-04-01"
output:
  html_document:
    df_print: paged
    fig_width: 10
    fig.align: center
    toc: true
    toc_depth: 4
    toc_float: true
    theme: united
    code_folding: show
---

<style>
body{text-align: justify}
</style>

# Introduction

```{r results = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(mnormt)
set.seed(123)
```

# Functions

```{r}
plot.sample.and.distribution.margins <- function(samples, dimension, mean, standard.deviations) {
  colnames(samples) <- as.character(seq(dimension))
  x.tibble <- as_tibble(samples) %>%
    mutate(p = seq(n())) %>%
    pivot_longer(
      cols = -p,
      names_to = "dimension",
      names_transform = as.integer,
      values_to = "x"
    )
  plot <- ggplot(
    data = tibble(
      dimension = seq(dimension),
      mean = mean,
      standard.deviations = standard.deviations
    ) %>%
      expand_grid(
        x = seq(-4, 4, 0.1)
      ) %>%
      group_by(dimension) %>%
      mutate(
        x = x * standard.deviations + mean,
        y = dnorm(
          x = x,
          mean = mean,
          sd = standard.deviations
        )
      ) %>%
      ungroup()
  ) +
    geom_line(
      mapping = aes(
        x = x,
        y = y
      ),
      linetype = "dotted"
    ) +
    geom_vline(
      mapping = aes(
        xintercept = mean
      )
    ) +
    geom_density(
      mapping = aes(
        x = x
      ),
      data = x.tibble,
      col = "darkgreen",
      fill = "darkgreen",
      alpha = 0.2
    ) +
    facet_wrap(
      facets = vars(dimension)
    )
  return(plot)
}
```

```{r}
plot.sample.and.distribution.covariance <- function(samples, dimension, mean, standard.deviations, correlation) {
  colnames(samples) <- as.character(seq(dimension))
  x.tibble <- as_tibble(samples) %>%
    mutate(p = seq(n())) %>%
    pivot_longer(
      cols = -p,
      names_to = "l",
      names_transform = as.integer,
      values_to = "x"
    )
  x.y.tibble <- x.tibble %>%
    full_join(
      x.tibble,
      by = "p",
      relationship = "many-to-many",
      suffix = c("1", "2")
    )
  plot <- ggplot(
    data = expand_grid(
      tibble(
        l1 = seq(dimension),
        mu1 = mean,
        sigma1 = standard.deviations
      ),
      tibble(
        l2 = seq(dimension),
        mu2 = mean,
        sigma2 = standard.deviations
      )
    ) %>%
      expand_grid(
        x1 = seq(-4, 4, 0.2),
        x2 = seq(-4, 4, 0.2)
      ) %>%
      mutate(
        correlation = 0.99 * correlation[cbind(l1, l2)],
        y = exp(-x1 * (x1 - correlation * x2) / (1 - correlation ^ 2) / 2 - x2 * (x2 - correlation * x1) / (1 - correlation ^ 2) / 2),
        x1 = x1 * sigma1 + mu1,
        x2 = x2 * sigma2 + mu2
      )
  ) +
    geom_contour(
      mapping = aes(
        x = x1,
        y = x2,
        z = y
      ),
      col = "black",
      linetype = "dotted",
      bins = 7
    ) +
    geom_vline(
      mapping = aes(
        xintercept = mu1
      )
    ) +
    geom_hline(
      mapping = aes(
        yintercept = mu2
      )
    ) +
    geom_density_2d(
      mapping = aes(
        x = x1,
        y = x2
      ),
      data = x.y.tibble,
      col = "darkgreen",
      contour_var = "ndensity",
      bins = 6
    ) +
    facet_grid(
      rows = vars(l1),
      cols = vars(l2)
    )
  return(plot)
}
```

```{r}
plot.sample.and.distribution.covariance.heatmap <- function(samples, dimension, covariance) {
  plot <- ggplot(
    mapping = aes(
      x = col,
      y = row,
      fill = value,
      label = sprintf("%.2f", value)
    ),
    data = tibble(
      source = "Analytical",
      row = rep(as.character(seq(dimension)), each = dimension),
      col = rep(as.character(seq(dimension)), times = dimension),
      value = c(covariance)
    ) %>%
      bind_rows(
        tibble(
          source = "Samples",
          row = rep(as.character(seq(dimension)), each = dimension),
          col = rep(as.character(seq(dimension)), times = dimension),
          value = c(cov(samples))
        )
      )
  ) +
    geom_tile(alpha = 0.7) +
    geom_text() +
    scale_fill_viridis_c() +
    guides(fill = "none") +
    labs(
      x = "",
      y = ""
    ) +
    facet_wrap(vars(source))
  return(plot)
}
```

```{r}
slow.function <- function(parameters, input.data) {
  output.data <- cbind(1, input.data) %*% t(parameters)
  return(output.data)
}
```

# Parameters

```{r}
input.dimension <- 5
output.dimension <- 3
n.monte.carlo <- 4000
delta <- 0.001
function.parameters <- matrix(runif((input.dimension + 1) * output.dimension, -1, 1), nrow = output.dimension)
function.parameters
```

# Input Data

```{r}
input.data.mean <- runif(input.dimension, -2, 3)
input.data.covariance.qr <- qr.Q(qr(matrix(rnorm(input.dimension ^ 2), input.dimension)))
input.data.covariance <- crossprod(input.data.covariance.qr, input.data.covariance.qr * seq(5, 1))
```

```{r}
input.data.standard.deviations <- sqrt(diag(input.data.covariance))
input.data.correlation <- t(input.data.covariance / input.data.standard.deviations) / input.data.standard.deviations
```

```{r}
input.data.monte.carlo.samples <- rmnorm(n.monte.carlo, input.data.mean, input.data.covariance)
```

# Visualise Input Data

```{r}
plot.sample.and.distribution.margins(input.data.monte.carlo.samples, input.dimension, input.data.mean, input.data.standard.deviations)
```

```{r}
plot.sample.and.distribution.covariance.heatmap(input.data.monte.carlo.samples, input.dimension, input.data.covariance)
```

```{r}
plot.sample.and.distribution.covariance(input.data.monte.carlo.samples, input.dimension, input.data.mean, input.data.standard.deviations, input.data.correlation)
```

# Slow Output Data

```{r}
output.data.monte.carlo.samples <- slow.function(function.parameters, input.data.monte.carlo.samples)
```

```{r}
output.data.monte.carlo.mean <- apply(output.data.monte.carlo.samples, 2, mean)
output.data.monte.carlo.mean
```

```{r}
output.data.monte.carlo.covariance <- cov(output.data.monte.carlo.samples)
output.data.monte.carlo.covariance
```

```{r}
output.data.monte.carlo.standard.deviations <- apply(output.data.monte.carlo.samples, 2, sd)
output.data.monte.carlo.standard.deviations
```

```{r}
output.data.monte.carlo.correlation <- cor(output.data.monte.carlo.samples)
output.data.monte.carlo.correlation
```

# Design of Experiment

```{r}
input.data.hypercube <- t(t(do.call(expand.grid, rep(list(c(0, delta)), input.dimension))) + input.data.mean)
input.data.linear.deltas <- t(t(rbind(rep(0, input.dimension), delta * diag(input.dimension))) + input.data.mean)
output.data.linear.deltas <- slow.function(function.parameters, input.data.linear.deltas)
intercept.and.jacobian <- unname(t(coef(lm(output.data.linear.deltas ~ 1 + input.data.linear.deltas))))
intercept <- intercept.and.jacobian[,1]
jacobian <- intercept.and.jacobian[,-1]
n.analytical <- nrow(input.data.linear.deltas)
n.analytical
```

# Surrogate Output Data

```{r}
output.data.analytical.mean <- intercept + c(matrix(input.data.mean, nrow = 1) %*% t(jacobian))
output.data.analytical.mean
```

```{r}
output.data.analytical.covariance <- jacobian %*% input.data.covariance %*% t(jacobian)
output.data.analytical.covariance
```

```{r}
output.data.analytical.standard.deviations <- sqrt(diag(output.data.analytical.covariance))
output.data.analytical.standard.deviations
```

```{r}
output.data.analytical.correlation <- t(output.data.analytical.covariance / output.data.analytical.standard.deviations) / output.data.analytical.standard.deviations
output.data.analytical.correlation
```

# Visualise Comparison

```{r}
plot.sample.and.distribution.margins(output.data.monte.carlo.samples, output.dimension, output.data.analytical.mean, output.data.analytical.standard.deviations)
```

```{r}
plot.sample.and.distribution.covariance.heatmap(output.data.monte.carlo.samples, output.dimension, output.data.analytical.covariance)
```

```{r}
plot.sample.and.distribution.covariance(output.data.monte.carlo.samples, output.dimension, output.data.analytical.mean, output.data.analytical.standard.deviations, output.data.analytical.correlation)
```
